import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/layouts/mainLayout";
import type { ChildrenProps } from "@/interfaces";

export const metadata: Metadata = {
  title: "Balkan Dreams",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
  return <MainLayout>{children}</MainLayout>;
}
