import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/layouts/mainLayout";

export const metadata: Metadata = {
  title: "Balkan Dreams",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <MainLayout>{children}</MainLayout>;
}
